// source: pi_wifi.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

goog.exportSymbol('proto.GetThisPiOnTheWiFi.v1.pi_wifi.DeviceDescription', null, global);
goog.exportSymbol('proto.GetThisPiOnTheWiFi.v1.pi_wifi.EmptyRequest', null, global);
goog.exportSymbol('proto.GetThisPiOnTheWiFi.v1.pi_wifi.EmptyResponse', null, global);
goog.exportSymbol('proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiRequest', null, global);
goog.exportSymbol('proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiRequest.RequestCase', null, global);
goog.exportSymbol('proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiResponse', null, global);
goog.exportSymbol('proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiResponse.ResponseCase', null, global);
goog.exportSymbol('proto.GetThisPiOnTheWiFi.v1.pi_wifi.SetWiFiDetails', null, global);
goog.exportSymbol('proto.GetThisPiOnTheWiFi.v1.pi_wifi.SuccessFailure', null, global);
goog.exportSymbol('proto.GetThisPiOnTheWiFi.v1.pi_wifi.WiFiStatus', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.EmptyRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.GetThisPiOnTheWiFi.v1.pi_wifi.EmptyRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.GetThisPiOnTheWiFi.v1.pi_wifi.EmptyRequest.displayName = 'proto.GetThisPiOnTheWiFi.v1.pi_wifi.EmptyRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.SetWiFiDetails = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.GetThisPiOnTheWiFi.v1.pi_wifi.SetWiFiDetails, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.GetThisPiOnTheWiFi.v1.pi_wifi.SetWiFiDetails.displayName = 'proto.GetThisPiOnTheWiFi.v1.pi_wifi.SetWiFiDetails';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiRequest.oneofGroups_);
};
goog.inherits(proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiRequest.displayName = 'proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.EmptyResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.GetThisPiOnTheWiFi.v1.pi_wifi.EmptyResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.GetThisPiOnTheWiFi.v1.pi_wifi.EmptyResponse.displayName = 'proto.GetThisPiOnTheWiFi.v1.pi_wifi.EmptyResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.SuccessFailure = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.GetThisPiOnTheWiFi.v1.pi_wifi.SuccessFailure, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.GetThisPiOnTheWiFi.v1.pi_wifi.SuccessFailure.displayName = 'proto.GetThisPiOnTheWiFi.v1.pi_wifi.SuccessFailure';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.DeviceDescription = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.GetThisPiOnTheWiFi.v1.pi_wifi.DeviceDescription, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.GetThisPiOnTheWiFi.v1.pi_wifi.DeviceDescription.displayName = 'proto.GetThisPiOnTheWiFi.v1.pi_wifi.DeviceDescription';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiResponse.oneofGroups_);
};
goog.inherits(proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiResponse.displayName = 'proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.EmptyRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.GetThisPiOnTheWiFi.v1.pi_wifi.EmptyRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.GetThisPiOnTheWiFi.v1.pi_wifi.EmptyRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.EmptyRequest.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.GetThisPiOnTheWiFi.v1.pi_wifi.EmptyRequest}
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.EmptyRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.GetThisPiOnTheWiFi.v1.pi_wifi.EmptyRequest;
  return proto.GetThisPiOnTheWiFi.v1.pi_wifi.EmptyRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.GetThisPiOnTheWiFi.v1.pi_wifi.EmptyRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.GetThisPiOnTheWiFi.v1.pi_wifi.EmptyRequest}
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.EmptyRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.EmptyRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.GetThisPiOnTheWiFi.v1.pi_wifi.EmptyRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.GetThisPiOnTheWiFi.v1.pi_wifi.EmptyRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.EmptyRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.SetWiFiDetails.prototype.toObject = function(opt_includeInstance) {
  return proto.GetThisPiOnTheWiFi.v1.pi_wifi.SetWiFiDetails.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.GetThisPiOnTheWiFi.v1.pi_wifi.SetWiFiDetails} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.SetWiFiDetails.toObject = function(includeInstance, msg) {
  var f, obj = {
    ssid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    password: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.GetThisPiOnTheWiFi.v1.pi_wifi.SetWiFiDetails}
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.SetWiFiDetails.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.GetThisPiOnTheWiFi.v1.pi_wifi.SetWiFiDetails;
  return proto.GetThisPiOnTheWiFi.v1.pi_wifi.SetWiFiDetails.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.GetThisPiOnTheWiFi.v1.pi_wifi.SetWiFiDetails} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.GetThisPiOnTheWiFi.v1.pi_wifi.SetWiFiDetails}
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.SetWiFiDetails.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSsid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setPassword(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.SetWiFiDetails.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.GetThisPiOnTheWiFi.v1.pi_wifi.SetWiFiDetails.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.GetThisPiOnTheWiFi.v1.pi_wifi.SetWiFiDetails} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.SetWiFiDetails.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSsid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPassword();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string ssid = 1;
 * @return {string}
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.SetWiFiDetails.prototype.getSsid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.GetThisPiOnTheWiFi.v1.pi_wifi.SetWiFiDetails} returns this
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.SetWiFiDetails.prototype.setSsid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string password = 2;
 * @return {string}
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.SetWiFiDetails.prototype.getPassword = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.GetThisPiOnTheWiFi.v1.pi_wifi.SetWiFiDetails} returns this
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.SetWiFiDetails.prototype.setPassword = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiRequest.oneofGroups_ = [[2,3]];

/**
 * @enum {number}
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiRequest.RequestCase = {
  REQUEST_NOT_SET: 0,
  GETDEVICEDESCRIPTION: 2,
  SETWIFIDETAILS: 3
};

/**
 * @return {proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiRequest.RequestCase}
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiRequest.prototype.getRequestCase = function() {
  return /** @type {proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiRequest.RequestCase} */(jspb.Message.computeOneofCase(this, proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiRequest.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    requestId: jspb.Message.getFieldWithDefault(msg, 1, 0),
    getdevicedescription: (f = msg.getGetdevicedescription()) && proto.GetThisPiOnTheWiFi.v1.pi_wifi.EmptyRequest.toObject(includeInstance, f),
    setwifidetails: (f = msg.getSetwifidetails()) && proto.GetThisPiOnTheWiFi.v1.pi_wifi.SetWiFiDetails.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiRequest}
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiRequest;
  return proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiRequest}
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setRequestId(value);
      break;
    case 2:
      var value = new proto.GetThisPiOnTheWiFi.v1.pi_wifi.EmptyRequest;
      reader.readMessage(value,proto.GetThisPiOnTheWiFi.v1.pi_wifi.EmptyRequest.deserializeBinaryFromReader);
      msg.setGetdevicedescription(value);
      break;
    case 3:
      var value = new proto.GetThisPiOnTheWiFi.v1.pi_wifi.SetWiFiDetails;
      reader.readMessage(value,proto.GetThisPiOnTheWiFi.v1.pi_wifi.SetWiFiDetails.deserializeBinaryFromReader);
      msg.setSetwifidetails(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRequestId();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getGetdevicedescription();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.GetThisPiOnTheWiFi.v1.pi_wifi.EmptyRequest.serializeBinaryToWriter
    );
  }
  f = message.getSetwifidetails();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.GetThisPiOnTheWiFi.v1.pi_wifi.SetWiFiDetails.serializeBinaryToWriter
    );
  }
};


/**
 * optional uint32 request_id = 1;
 * @return {number}
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiRequest.prototype.getRequestId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiRequest} returns this
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiRequest.prototype.setRequestId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional EmptyRequest getDeviceDescription = 2;
 * @return {?proto.GetThisPiOnTheWiFi.v1.pi_wifi.EmptyRequest}
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiRequest.prototype.getGetdevicedescription = function() {
  return /** @type{?proto.GetThisPiOnTheWiFi.v1.pi_wifi.EmptyRequest} */ (
    jspb.Message.getWrapperField(this, proto.GetThisPiOnTheWiFi.v1.pi_wifi.EmptyRequest, 2));
};


/**
 * @param {?proto.GetThisPiOnTheWiFi.v1.pi_wifi.EmptyRequest|undefined} value
 * @return {!proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiRequest} returns this
*/
proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiRequest.prototype.setGetdevicedescription = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiRequest.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiRequest} returns this
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiRequest.prototype.clearGetdevicedescription = function() {
  return this.setGetdevicedescription(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiRequest.prototype.hasGetdevicedescription = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional SetWiFiDetails setWiFiDetails = 3;
 * @return {?proto.GetThisPiOnTheWiFi.v1.pi_wifi.SetWiFiDetails}
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiRequest.prototype.getSetwifidetails = function() {
  return /** @type{?proto.GetThisPiOnTheWiFi.v1.pi_wifi.SetWiFiDetails} */ (
    jspb.Message.getWrapperField(this, proto.GetThisPiOnTheWiFi.v1.pi_wifi.SetWiFiDetails, 3));
};


/**
 * @param {?proto.GetThisPiOnTheWiFi.v1.pi_wifi.SetWiFiDetails|undefined} value
 * @return {!proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiRequest} returns this
*/
proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiRequest.prototype.setSetwifidetails = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiRequest.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiRequest} returns this
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiRequest.prototype.clearSetwifidetails = function() {
  return this.setSetwifidetails(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiRequest.prototype.hasSetwifidetails = function() {
  return jspb.Message.getField(this, 3) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.EmptyResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.GetThisPiOnTheWiFi.v1.pi_wifi.EmptyResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.GetThisPiOnTheWiFi.v1.pi_wifi.EmptyResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.EmptyResponse.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.GetThisPiOnTheWiFi.v1.pi_wifi.EmptyResponse}
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.EmptyResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.GetThisPiOnTheWiFi.v1.pi_wifi.EmptyResponse;
  return proto.GetThisPiOnTheWiFi.v1.pi_wifi.EmptyResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.GetThisPiOnTheWiFi.v1.pi_wifi.EmptyResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.GetThisPiOnTheWiFi.v1.pi_wifi.EmptyResponse}
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.EmptyResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.EmptyResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.GetThisPiOnTheWiFi.v1.pi_wifi.EmptyResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.GetThisPiOnTheWiFi.v1.pi_wifi.EmptyResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.EmptyResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.SuccessFailure.prototype.toObject = function(opt_includeInstance) {
  return proto.GetThisPiOnTheWiFi.v1.pi_wifi.SuccessFailure.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.GetThisPiOnTheWiFi.v1.pi_wifi.SuccessFailure} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.SuccessFailure.toObject = function(includeInstance, msg) {
  var f, obj = {
    success: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
    error: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.GetThisPiOnTheWiFi.v1.pi_wifi.SuccessFailure}
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.SuccessFailure.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.GetThisPiOnTheWiFi.v1.pi_wifi.SuccessFailure;
  return proto.GetThisPiOnTheWiFi.v1.pi_wifi.SuccessFailure.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.GetThisPiOnTheWiFi.v1.pi_wifi.SuccessFailure} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.GetThisPiOnTheWiFi.v1.pi_wifi.SuccessFailure}
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.SuccessFailure.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSuccess(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setError(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.SuccessFailure.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.GetThisPiOnTheWiFi.v1.pi_wifi.SuccessFailure.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.GetThisPiOnTheWiFi.v1.pi_wifi.SuccessFailure} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.SuccessFailure.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSuccess();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getError();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional bool success = 1;
 * @return {boolean}
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.SuccessFailure.prototype.getSuccess = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.GetThisPiOnTheWiFi.v1.pi_wifi.SuccessFailure} returns this
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.SuccessFailure.prototype.setSuccess = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional string error = 2;
 * @return {string}
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.SuccessFailure.prototype.getError = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.GetThisPiOnTheWiFi.v1.pi_wifi.SuccessFailure} returns this
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.SuccessFailure.prototype.setError = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.DeviceDescription.prototype.toObject = function(opt_includeInstance) {
  return proto.GetThisPiOnTheWiFi.v1.pi_wifi.DeviceDescription.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.GetThisPiOnTheWiFi.v1.pi_wifi.DeviceDescription} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.DeviceDescription.toObject = function(includeInstance, msg) {
  var f, obj = {
    devicename: jspb.Message.getFieldWithDefault(msg, 1, ""),
    devicewifiname: jspb.Message.getFieldWithDefault(msg, 2, ""),
    wifistatus: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.GetThisPiOnTheWiFi.v1.pi_wifi.DeviceDescription}
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.DeviceDescription.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.GetThisPiOnTheWiFi.v1.pi_wifi.DeviceDescription;
  return proto.GetThisPiOnTheWiFi.v1.pi_wifi.DeviceDescription.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.GetThisPiOnTheWiFi.v1.pi_wifi.DeviceDescription} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.GetThisPiOnTheWiFi.v1.pi_wifi.DeviceDescription}
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.DeviceDescription.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setDevicename(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setDevicewifiname(value);
      break;
    case 3:
      var value = /** @type {!proto.GetThisPiOnTheWiFi.v1.pi_wifi.WiFiStatus} */ (reader.readEnum());
      msg.setWifistatus(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.DeviceDescription.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.GetThisPiOnTheWiFi.v1.pi_wifi.DeviceDescription.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.GetThisPiOnTheWiFi.v1.pi_wifi.DeviceDescription} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.DeviceDescription.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDevicename();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getDevicewifiname();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getWifistatus();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
};


/**
 * optional string deviceName = 1;
 * @return {string}
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.DeviceDescription.prototype.getDevicename = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.GetThisPiOnTheWiFi.v1.pi_wifi.DeviceDescription} returns this
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.DeviceDescription.prototype.setDevicename = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string deviceWiFiName = 2;
 * @return {string}
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.DeviceDescription.prototype.getDevicewifiname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.GetThisPiOnTheWiFi.v1.pi_wifi.DeviceDescription} returns this
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.DeviceDescription.prototype.setDevicewifiname = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional WiFiStatus wiFiStatus = 3;
 * @return {!proto.GetThisPiOnTheWiFi.v1.pi_wifi.WiFiStatus}
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.DeviceDescription.prototype.getWifistatus = function() {
  return /** @type {!proto.GetThisPiOnTheWiFi.v1.pi_wifi.WiFiStatus} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.GetThisPiOnTheWiFi.v1.pi_wifi.WiFiStatus} value
 * @return {!proto.GetThisPiOnTheWiFi.v1.pi_wifi.DeviceDescription} returns this
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.DeviceDescription.prototype.setWifistatus = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiResponse.oneofGroups_ = [[3,4]];

/**
 * @enum {number}
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiResponse.ResponseCase = {
  RESPONSE_NOT_SET: 0,
  DEVICEDESCRIPTION: 3,
  SETWIFIDETAILSRESPONSE: 4
};

/**
 * @return {proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiResponse.ResponseCase}
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiResponse.prototype.getResponseCase = function() {
  return /** @type {proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiResponse.ResponseCase} */(jspb.Message.computeOneofCase(this, proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiResponse.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    responseId: jspb.Message.getFieldWithDefault(msg, 1, 0),
    status: (f = msg.getStatus()) && proto.GetThisPiOnTheWiFi.v1.pi_wifi.SuccessFailure.toObject(includeInstance, f),
    devicedescription: (f = msg.getDevicedescription()) && proto.GetThisPiOnTheWiFi.v1.pi_wifi.DeviceDescription.toObject(includeInstance, f),
    setwifidetailsresponse: (f = msg.getSetwifidetailsresponse()) && proto.GetThisPiOnTheWiFi.v1.pi_wifi.EmptyResponse.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiResponse}
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiResponse;
  return proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiResponse}
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setResponseId(value);
      break;
    case 2:
      var value = new proto.GetThisPiOnTheWiFi.v1.pi_wifi.SuccessFailure;
      reader.readMessage(value,proto.GetThisPiOnTheWiFi.v1.pi_wifi.SuccessFailure.deserializeBinaryFromReader);
      msg.setStatus(value);
      break;
    case 3:
      var value = new proto.GetThisPiOnTheWiFi.v1.pi_wifi.DeviceDescription;
      reader.readMessage(value,proto.GetThisPiOnTheWiFi.v1.pi_wifi.DeviceDescription.deserializeBinaryFromReader);
      msg.setDevicedescription(value);
      break;
    case 4:
      var value = new proto.GetThisPiOnTheWiFi.v1.pi_wifi.EmptyResponse;
      reader.readMessage(value,proto.GetThisPiOnTheWiFi.v1.pi_wifi.EmptyResponse.deserializeBinaryFromReader);
      msg.setSetwifidetailsresponse(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getResponseId();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getStatus();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.GetThisPiOnTheWiFi.v1.pi_wifi.SuccessFailure.serializeBinaryToWriter
    );
  }
  f = message.getDevicedescription();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.GetThisPiOnTheWiFi.v1.pi_wifi.DeviceDescription.serializeBinaryToWriter
    );
  }
  f = message.getSetwifidetailsresponse();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.GetThisPiOnTheWiFi.v1.pi_wifi.EmptyResponse.serializeBinaryToWriter
    );
  }
};


/**
 * optional uint32 response_id = 1;
 * @return {number}
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiResponse.prototype.getResponseId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiResponse} returns this
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiResponse.prototype.setResponseId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional SuccessFailure status = 2;
 * @return {?proto.GetThisPiOnTheWiFi.v1.pi_wifi.SuccessFailure}
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiResponse.prototype.getStatus = function() {
  return /** @type{?proto.GetThisPiOnTheWiFi.v1.pi_wifi.SuccessFailure} */ (
    jspb.Message.getWrapperField(this, proto.GetThisPiOnTheWiFi.v1.pi_wifi.SuccessFailure, 2));
};


/**
 * @param {?proto.GetThisPiOnTheWiFi.v1.pi_wifi.SuccessFailure|undefined} value
 * @return {!proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiResponse} returns this
*/
proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiResponse.prototype.setStatus = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiResponse} returns this
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiResponse.prototype.clearStatus = function() {
  return this.setStatus(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiResponse.prototype.hasStatus = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional DeviceDescription deviceDescription = 3;
 * @return {?proto.GetThisPiOnTheWiFi.v1.pi_wifi.DeviceDescription}
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiResponse.prototype.getDevicedescription = function() {
  return /** @type{?proto.GetThisPiOnTheWiFi.v1.pi_wifi.DeviceDescription} */ (
    jspb.Message.getWrapperField(this, proto.GetThisPiOnTheWiFi.v1.pi_wifi.DeviceDescription, 3));
};


/**
 * @param {?proto.GetThisPiOnTheWiFi.v1.pi_wifi.DeviceDescription|undefined} value
 * @return {!proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiResponse} returns this
*/
proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiResponse.prototype.setDevicedescription = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiResponse.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiResponse} returns this
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiResponse.prototype.clearDevicedescription = function() {
  return this.setDevicedescription(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiResponse.prototype.hasDevicedescription = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional EmptyResponse setWiFiDetailsResponse = 4;
 * @return {?proto.GetThisPiOnTheWiFi.v1.pi_wifi.EmptyResponse}
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiResponse.prototype.getSetwifidetailsresponse = function() {
  return /** @type{?proto.GetThisPiOnTheWiFi.v1.pi_wifi.EmptyResponse} */ (
    jspb.Message.getWrapperField(this, proto.GetThisPiOnTheWiFi.v1.pi_wifi.EmptyResponse, 4));
};


/**
 * @param {?proto.GetThisPiOnTheWiFi.v1.pi_wifi.EmptyResponse|undefined} value
 * @return {!proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiResponse} returns this
*/
proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiResponse.prototype.setSetwifidetailsresponse = function(value) {
  return jspb.Message.setOneofWrapperField(this, 4, proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiResponse.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiResponse} returns this
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiResponse.prototype.clearSetwifidetailsresponse = function() {
  return this.setSetwifidetailsresponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiResponse.prototype.hasSetwifidetailsresponse = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * @enum {number}
 */
proto.GetThisPiOnTheWiFi.v1.pi_wifi.WiFiStatus = {
  DISCONNECTING: 0,
  SETTING: 1,
  RESTARTING: 2,
  CONNECTING: 3,
  CONNECTED: 4
};

goog.object.extend(exports, proto.GetThisPiOnTheWiFi.v1.pi_wifi);
