// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: pi_wifi.proto

package protoPiWiFi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WiFiStatus int32

const (
	WiFiStatus_DISCONNECTING WiFiStatus = 0
	WiFiStatus_SETTING       WiFiStatus = 1
	WiFiStatus_RESTARTING    WiFiStatus = 2
	WiFiStatus_CONNECTING    WiFiStatus = 3
	WiFiStatus_CONNECTED     WiFiStatus = 4
)

// Enum value maps for WiFiStatus.
var (
	WiFiStatus_name = map[int32]string{
		0: "DISCONNECTING",
		1: "SETTING",
		2: "RESTARTING",
		3: "CONNECTING",
		4: "CONNECTED",
	}
	WiFiStatus_value = map[string]int32{
		"DISCONNECTING": 0,
		"SETTING":       1,
		"RESTARTING":    2,
		"CONNECTING":    3,
		"CONNECTED":     4,
	}
)

func (x WiFiStatus) Enum() *WiFiStatus {
	p := new(WiFiStatus)
	*p = x
	return p
}

func (x WiFiStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WiFiStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pi_wifi_proto_enumTypes[0].Descriptor()
}

func (WiFiStatus) Type() protoreflect.EnumType {
	return &file_pi_wifi_proto_enumTypes[0]
}

func (x WiFiStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WiFiStatus.Descriptor instead.
func (WiFiStatus) EnumDescriptor() ([]byte, []int) {
	return file_pi_wifi_proto_rawDescGZIP(), []int{0}
}

type EmptyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pi_wifi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pi_wifi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_pi_wifi_proto_rawDescGZIP(), []int{0}
}

type SetWiFiDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ssid     string `protobuf:"bytes,1,opt,name=ssid,proto3" json:"ssid,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *SetWiFiDetails) Reset() {
	*x = SetWiFiDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pi_wifi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetWiFiDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetWiFiDetails) ProtoMessage() {}

func (x *SetWiFiDetails) ProtoReflect() protoreflect.Message {
	mi := &file_pi_wifi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetWiFiDetails.ProtoReflect.Descriptor instead.
func (*SetWiFiDetails) Descriptor() ([]byte, []int) {
	return file_pi_wifi_proto_rawDescGZIP(), []int{1}
}

func (x *SetWiFiDetails) GetSsid() string {
	if x != nil {
		return x.Ssid
	}
	return ""
}

func (x *SetWiFiDetails) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type PiWiFiRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId uint32 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are assignable to Request:
	//	*PiWiFiRequest_GetDeviceDescription
	//	*PiWiFiRequest_SetWiFiDetails
	Request isPiWiFiRequest_Request `protobuf_oneof:"request"`
}

func (x *PiWiFiRequest) Reset() {
	*x = PiWiFiRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pi_wifi_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PiWiFiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PiWiFiRequest) ProtoMessage() {}

func (x *PiWiFiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pi_wifi_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PiWiFiRequest.ProtoReflect.Descriptor instead.
func (*PiWiFiRequest) Descriptor() ([]byte, []int) {
	return file_pi_wifi_proto_rawDescGZIP(), []int{2}
}

func (x *PiWiFiRequest) GetRequestId() uint32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (m *PiWiFiRequest) GetRequest() isPiWiFiRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (x *PiWiFiRequest) GetGetDeviceDescription() *EmptyRequest {
	if x, ok := x.GetRequest().(*PiWiFiRequest_GetDeviceDescription); ok {
		return x.GetDeviceDescription
	}
	return nil
}

func (x *PiWiFiRequest) GetSetWiFiDetails() *SetWiFiDetails {
	if x, ok := x.GetRequest().(*PiWiFiRequest_SetWiFiDetails); ok {
		return x.SetWiFiDetails
	}
	return nil
}

type isPiWiFiRequest_Request interface {
	isPiWiFiRequest_Request()
}

type PiWiFiRequest_GetDeviceDescription struct {
	GetDeviceDescription *EmptyRequest `protobuf:"bytes,2,opt,name=getDeviceDescription,proto3,oneof"`
}

type PiWiFiRequest_SetWiFiDetails struct {
	SetWiFiDetails *SetWiFiDetails `protobuf:"bytes,3,opt,name=setWiFiDetails,proto3,oneof"`
}

func (*PiWiFiRequest_GetDeviceDescription) isPiWiFiRequest_Request() {}

func (*PiWiFiRequest_SetWiFiDetails) isPiWiFiRequest_Request() {}

type EmptyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyResponse) Reset() {
	*x = EmptyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pi_wifi_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyResponse) ProtoMessage() {}

func (x *EmptyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pi_wifi_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyResponse.ProtoReflect.Descriptor instead.
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return file_pi_wifi_proto_rawDescGZIP(), []int{3}
}

type SuccessFailure struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *SuccessFailure) Reset() {
	*x = SuccessFailure{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pi_wifi_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SuccessFailure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuccessFailure) ProtoMessage() {}

func (x *SuccessFailure) ProtoReflect() protoreflect.Message {
	mi := &file_pi_wifi_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuccessFailure.ProtoReflect.Descriptor instead.
func (*SuccessFailure) Descriptor() ([]byte, []int) {
	return file_pi_wifi_proto_rawDescGZIP(), []int{4}
}

func (x *SuccessFailure) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SuccessFailure) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeviceDescription struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceName     string     `protobuf:"bytes,1,opt,name=deviceName,proto3" json:"deviceName,omitempty"`
	DeviceWiFiName string     `protobuf:"bytes,2,opt,name=deviceWiFiName,proto3" json:"deviceWiFiName,omitempty"`
	WiFiStatus     WiFiStatus `protobuf:"varint,3,opt,name=wiFiStatus,proto3,enum=GetThisPiOnTheWiFi.v1.pi_wifi.WiFiStatus" json:"wiFiStatus,omitempty"`
}

func (x *DeviceDescription) Reset() {
	*x = DeviceDescription{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pi_wifi_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceDescription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceDescription) ProtoMessage() {}

func (x *DeviceDescription) ProtoReflect() protoreflect.Message {
	mi := &file_pi_wifi_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceDescription.ProtoReflect.Descriptor instead.
func (*DeviceDescription) Descriptor() ([]byte, []int) {
	return file_pi_wifi_proto_rawDescGZIP(), []int{5}
}

func (x *DeviceDescription) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *DeviceDescription) GetDeviceWiFiName() string {
	if x != nil {
		return x.DeviceWiFiName
	}
	return ""
}

func (x *DeviceDescription) GetWiFiStatus() WiFiStatus {
	if x != nil {
		return x.WiFiStatus
	}
	return WiFiStatus_DISCONNECTING
}

type PiWiFiResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResponseId uint32          `protobuf:"varint,1,opt,name=response_id,json=responseId,proto3" json:"response_id,omitempty"`
	Status     *SuccessFailure `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// Types that are assignable to Response:
	//	*PiWiFiResponse_DeviceDescription
	//	*PiWiFiResponse_SetWiFiDetailsResponse
	Response isPiWiFiResponse_Response `protobuf_oneof:"response"`
}

func (x *PiWiFiResponse) Reset() {
	*x = PiWiFiResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pi_wifi_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PiWiFiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PiWiFiResponse) ProtoMessage() {}

func (x *PiWiFiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pi_wifi_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PiWiFiResponse.ProtoReflect.Descriptor instead.
func (*PiWiFiResponse) Descriptor() ([]byte, []int) {
	return file_pi_wifi_proto_rawDescGZIP(), []int{6}
}

func (x *PiWiFiResponse) GetResponseId() uint32 {
	if x != nil {
		return x.ResponseId
	}
	return 0
}

func (x *PiWiFiResponse) GetStatus() *SuccessFailure {
	if x != nil {
		return x.Status
	}
	return nil
}

func (m *PiWiFiResponse) GetResponse() isPiWiFiResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *PiWiFiResponse) GetDeviceDescription() *DeviceDescription {
	if x, ok := x.GetResponse().(*PiWiFiResponse_DeviceDescription); ok {
		return x.DeviceDescription
	}
	return nil
}

func (x *PiWiFiResponse) GetSetWiFiDetailsResponse() *EmptyResponse {
	if x, ok := x.GetResponse().(*PiWiFiResponse_SetWiFiDetailsResponse); ok {
		return x.SetWiFiDetailsResponse
	}
	return nil
}

type isPiWiFiResponse_Response interface {
	isPiWiFiResponse_Response()
}

type PiWiFiResponse_DeviceDescription struct {
	DeviceDescription *DeviceDescription `protobuf:"bytes,3,opt,name=deviceDescription,proto3,oneof"`
}

type PiWiFiResponse_SetWiFiDetailsResponse struct {
	SetWiFiDetailsResponse *EmptyResponse `protobuf:"bytes,4,opt,name=setWiFiDetailsResponse,proto3,oneof"`
}

func (*PiWiFiResponse_DeviceDescription) isPiWiFiResponse_Response() {}

func (*PiWiFiResponse_SetWiFiDetailsResponse) isPiWiFiResponse_Response() {}

var File_pi_wifi_proto protoreflect.FileDescriptor

var file_pi_wifi_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x70, 0x69, 0x5f, 0x77, 0x69, 0x66, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x1d, 0x47, 0x65, 0x74, 0x54, 0x68, 0x69, 0x73, 0x50, 0x69, 0x4f, 0x6e, 0x54, 0x68, 0x65, 0x57,
	0x69, 0x46, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x69, 0x5f, 0x77, 0x69, 0x66, 0x69, 0x22, 0x0e,
	0x0a, 0x0c, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x40,
	0x0a, 0x0e, 0x53, 0x65, 0x74, 0x57, 0x69, 0x46, 0x69, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x73, 0x73, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x73, 0x73, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x22, 0xf5, 0x01, 0x0a, 0x0d, 0x50, 0x69, 0x57, 0x69, 0x46, 0x69, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49,
	0x64, 0x12, 0x61, 0x0a, 0x14, 0x67, 0x65, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x2b, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x68, 0x69, 0x73, 0x50, 0x69, 0x4f, 0x6e, 0x54, 0x68, 0x65,
	0x57, 0x69, 0x46, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x69, 0x5f, 0x77, 0x69, 0x66, 0x69, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x14,
	0x67, 0x65, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x57, 0x0a, 0x0e, 0x73, 0x65, 0x74, 0x57, 0x69, 0x46, 0x69, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x47,
	0x65, 0x74, 0x54, 0x68, 0x69, 0x73, 0x50, 0x69, 0x4f, 0x6e, 0x54, 0x68, 0x65, 0x57, 0x69, 0x46,
	0x69, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x69, 0x5f, 0x77, 0x69, 0x66, 0x69, 0x2e, 0x53, 0x65, 0x74,
	0x57, 0x69, 0x46, 0x69, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x48, 0x00, 0x52, 0x0e, 0x73,
	0x65, 0x74, 0x57, 0x69, 0x46, 0x69, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x42, 0x09, 0x0a,
	0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0f, 0x0a, 0x0d, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x40, 0x0a, 0x0e, 0x53, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x46, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0xa6, 0x01, 0x0a, 0x11,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x26, 0x0a, 0x0e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x57, 0x69, 0x46, 0x69, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x57, 0x69, 0x46, 0x69, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x49, 0x0a, 0x0a, 0x77, 0x69, 0x46,
	0x69, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x29, 0x2e,
	0x47, 0x65, 0x74, 0x54, 0x68, 0x69, 0x73, 0x50, 0x69, 0x4f, 0x6e, 0x54, 0x68, 0x65, 0x57, 0x69,
	0x46, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x69, 0x5f, 0x77, 0x69, 0x66, 0x69, 0x2e, 0x57, 0x69,
	0x46, 0x69, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0a, 0x77, 0x69, 0x46, 0x69, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x22, 0xce, 0x02, 0x0a, 0x0e, 0x50, 0x69, 0x57, 0x69, 0x46, 0x69, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x49, 0x64, 0x12, 0x45, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x68,
	0x69, 0x73, 0x50, 0x69, 0x4f, 0x6e, 0x54, 0x68, 0x65, 0x57, 0x69, 0x46, 0x69, 0x2e, 0x76, 0x31,
	0x2e, 0x70, 0x69, 0x5f, 0x77, 0x69, 0x66, 0x69, 0x2e, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x46, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x60, 0x0a, 0x11, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x47, 0x65, 0x74,
	0x54, 0x68, 0x69, 0x73, 0x50, 0x69, 0x4f, 0x6e, 0x54, 0x68, 0x65, 0x57, 0x69, 0x46, 0x69, 0x2e,
	0x76, 0x31, 0x2e, 0x70, 0x69, 0x5f, 0x77, 0x69, 0x66, 0x69, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x11,
	0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x66, 0x0a, 0x16, 0x73, 0x65, 0x74, 0x57, 0x69, 0x46, 0x69, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x2c, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x68, 0x69, 0x73, 0x50, 0x69, 0x4f, 0x6e, 0x54,
	0x68, 0x65, 0x57, 0x69, 0x46, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x69, 0x5f, 0x77, 0x69, 0x66,
	0x69, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48,
	0x00, 0x52, 0x16, 0x73, 0x65, 0x74, 0x57, 0x69, 0x46, 0x69, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2a, 0x5b, 0x0a, 0x0a, 0x57, 0x69, 0x46, 0x69, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x11, 0x0a, 0x0d, 0x44, 0x49, 0x53, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43,
	0x54, 0x49, 0x4e, 0x47, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x45, 0x54, 0x54, 0x49, 0x4e,
	0x47, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x52, 0x45, 0x53, 0x54, 0x41, 0x52, 0x54, 0x49, 0x4e,
	0x47, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x49, 0x4e,
	0x47, 0x10, 0x03, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x45, 0x44,
	0x10, 0x04, 0x42, 0x4f, 0x5a, 0x4d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x62, 0x72, 0x6f, 0x6f, 0x73, 0x65, 0x2d, 0x67, 0x6f, 0x6f, 0x73, 0x65, 0x2f, 0x47, 0x65,
	0x74, 0x2d, 0x54, 0x68, 0x69, 0x73, 0x2d, 0x50, 0x69, 0x2d, 0x4f, 0x6e, 0x2d, 0x54, 0x68, 0x65,
	0x2d, 0x57, 0x69, 0x46, 0x69, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x6f, 0x2f,
	0x70, 0x69, 0x5f, 0x77, 0x69, 0x66, 0x69, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x69, 0x57,
	0x69, 0x46, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pi_wifi_proto_rawDescOnce sync.Once
	file_pi_wifi_proto_rawDescData = file_pi_wifi_proto_rawDesc
)

func file_pi_wifi_proto_rawDescGZIP() []byte {
	file_pi_wifi_proto_rawDescOnce.Do(func() {
		file_pi_wifi_proto_rawDescData = protoimpl.X.CompressGZIP(file_pi_wifi_proto_rawDescData)
	})
	return file_pi_wifi_proto_rawDescData
}

var file_pi_wifi_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pi_wifi_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pi_wifi_proto_goTypes = []interface{}{
	(WiFiStatus)(0),           // 0: GetThisPiOnTheWiFi.v1.pi_wifi.WiFiStatus
	(*EmptyRequest)(nil),      // 1: GetThisPiOnTheWiFi.v1.pi_wifi.EmptyRequest
	(*SetWiFiDetails)(nil),    // 2: GetThisPiOnTheWiFi.v1.pi_wifi.SetWiFiDetails
	(*PiWiFiRequest)(nil),     // 3: GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiRequest
	(*EmptyResponse)(nil),     // 4: GetThisPiOnTheWiFi.v1.pi_wifi.EmptyResponse
	(*SuccessFailure)(nil),    // 5: GetThisPiOnTheWiFi.v1.pi_wifi.SuccessFailure
	(*DeviceDescription)(nil), // 6: GetThisPiOnTheWiFi.v1.pi_wifi.DeviceDescription
	(*PiWiFiResponse)(nil),    // 7: GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiResponse
}
var file_pi_wifi_proto_depIdxs = []int32{
	1, // 0: GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiRequest.getDeviceDescription:type_name -> GetThisPiOnTheWiFi.v1.pi_wifi.EmptyRequest
	2, // 1: GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiRequest.setWiFiDetails:type_name -> GetThisPiOnTheWiFi.v1.pi_wifi.SetWiFiDetails
	0, // 2: GetThisPiOnTheWiFi.v1.pi_wifi.DeviceDescription.wiFiStatus:type_name -> GetThisPiOnTheWiFi.v1.pi_wifi.WiFiStatus
	5, // 3: GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiResponse.status:type_name -> GetThisPiOnTheWiFi.v1.pi_wifi.SuccessFailure
	6, // 4: GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiResponse.deviceDescription:type_name -> GetThisPiOnTheWiFi.v1.pi_wifi.DeviceDescription
	4, // 5: GetThisPiOnTheWiFi.v1.pi_wifi.PiWiFiResponse.setWiFiDetailsResponse:type_name -> GetThisPiOnTheWiFi.v1.pi_wifi.EmptyResponse
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_pi_wifi_proto_init() }
func file_pi_wifi_proto_init() {
	if File_pi_wifi_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pi_wifi_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pi_wifi_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetWiFiDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pi_wifi_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PiWiFiRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pi_wifi_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pi_wifi_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SuccessFailure); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pi_wifi_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceDescription); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pi_wifi_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PiWiFiResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pi_wifi_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*PiWiFiRequest_GetDeviceDescription)(nil),
		(*PiWiFiRequest_SetWiFiDetails)(nil),
	}
	file_pi_wifi_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*PiWiFiResponse_DeviceDescription)(nil),
		(*PiWiFiResponse_SetWiFiDetailsResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pi_wifi_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pi_wifi_proto_goTypes,
		DependencyIndexes: file_pi_wifi_proto_depIdxs,
		EnumInfos:         file_pi_wifi_proto_enumTypes,
		MessageInfos:      file_pi_wifi_proto_msgTypes,
	}.Build()
	File_pi_wifi_proto = out.File
	file_pi_wifi_proto_rawDesc = nil
	file_pi_wifi_proto_goTypes = nil
	file_pi_wifi_proto_depIdxs = nil
}
